### ISSUE TITLE
Matching failure for expect_request 

### ISSUE THREAD

**Issue by matez0** [csernazs/pytest-httpserver#115]
pytest-httpserver==1.0.4

I would like to use `pytest_httpserver` in behave by instantiating `HTTPServer`.
When I use the `expect_request method`, the matching does not work.
Curiously, it works for `expect_oneshot_request`.

Reproduction of issue:
```python
from pytest_httpserver import HTTPServer
import requests


def test_wait():
    with HTTPServer() as httpserver:
        httpserver.expect_request('/x').respond_with_json({})
        with httpserver.wait(timeout=2) as waiting:
            requests.get(httpserver.url_for('/x'))
        assert waiting.result
```
Run:
```
pytest test.py
```
Output:
```
E               AssertionError: Wait timeout occurred, but some handlers left:
E               Ordered matchers:
E                   none
E               
E               Oneshot matchers:
E                   none
E               
E               Persistent matchers:
E                   <RequestMatcher uri='/x' method='__ALL' query_string=None headers={} data=None json=<UNDEFINED>>

.venv/lib/python3.8/site-packages/pytest_httpserver/httpserver.py:1121: AssertionError
-------------------------------------------------------------------------------- Captured log call --------------------------------------------------------------------------------
INFO     werkzeug:_internal.py:224 127.0.0.1 - - [08/Apr/2022 14:03:32] "GET /x HTTP/1.1" 200 -
```

**Comment by csernazs** [comment]
Hi there,

This waiting mechanism was designed for oneshot and ordered matchers only, as only for these you can determine when event when they are "exhausted". For the normal matchers, which can be triggered in arbitrary order for as many times as you want, it is hard to define when those are exhausted. If you think that it should serve only one request, you should use the oneshot matcher as it is designed for that.

This is documented here: https://pytest-httpserver.readthedocs.io/en/latest/howto.html#multi-threading-support

> This is available only for oneshot and ordered handlers, as permanent handlers last forever.

Does this answer your question?

**Comment by matez0** [comment]
Hi,
Thank you for the explanation.
I remembered some example not well and missed this info when reading the documentation.
