### ISSUE TITLE
1.0.4: sphinx fails because directories layout issue

### ISSUE THREAD

**Issue by kloczek** [csernazs/pytest-httpserver#117]
Looks like sphinx is failing because directories layaout issue has been found.
```console
+ /usr/bin/python3 -sBm build -w --no-isolation
* Getting dependencies for wheel...
* Building wheel...
Successfully built pytest_httpserver-1.0.4-py3-none-any.whl
+ '[' '!' -f setup.py ']'
+ DELETE_SETUP_PY=yes
+ echo 'from setuptools import setup; setup()'
+ PBR_VERSION=1.0.4
+ SETUPTOOLS_SCM_PRETEND_VERSION=1.0.4
+ /usr/bin/python3 setup.py build_sphinx -b man --build-dir build/sphinx
error: Multiple top-level packages discovered in a flat-layout: ['releasenotes', 'pytest_httpserver'].

To avoid accidental inclusion of unwanted files or directories,
setuptools will not proceed with this build.

If you are trying to create a single distribution with multiple packages
on purpose, you should not rely on automatic discovery.
Instead, consider the following options:

1. set up custom discovery (`find` directive with `include` or `exclude`)
2. use a `src-layout`
3. explicitly set `py_modules` or `packages` with a list of names

To find more information, look for "package discovery" on setuptools docs.
```

**Comment by csernazs** [comment]
Hi,

Could you please share a bit of context? How are you trying to build this and what tool are you using?

I use `make dev doc` to build the documentation and it works well for me and this is used to build the official documentation on readthedocs.org.

**Comment by kloczek** [comment]
I think that I know what caused that effect and  it is not any issue in your module.
To be able use setuptools<>sphinx integration to build sphinx documentation in kind of unified way I'm injecting dummy setup.py `echo 'from setuptools import setup; setup()' > setup.py` in case when that file is not present. This part of my rpm macro `%py3_build_sphinx_man`.
In case of your module `poetry-core` is used as pep517 backend and that message is result of that injection.
That tric is not at least affection those modules which are usinf `flit-core`

That is really shame that `poetry`, `whey`, `hatchlings` and few other do not take care of building documentation in unifird way 😞 

Closing ..
