### ISSUE TITLE
howto response more than one cookie

### ISSUE THREAD

**Issue by albertix** [csernazs/pytest-httpserver#132]
i can response one cookie with

`respond_with_data(headers={"Set-Cookie":"somecookie=somevalue;"})`

but how can i make a response with more than one cookies?

**Comment by csernazs** [comment]
You can find the examples in the [test](https://github.com/csernazs/pytest-httpserver/blob/8704fb092261a2ec7c1e9d6242288a7320190fee/tests/test_headers.py#L79). Only the type hint was modified so if you don't use type checker then you can use it now with the currently released version.
