### ISSUE TITLE
query_string as binary string

### ISSUE THREAD

**Issue by UrmelAusDemEis** [csernazs/pytest-httpserver#16]
Hey!

The query_string in your [RequestMatcher](https://github.com/csernazs/pytest-httpserver/blob/32e1b2c9a005b1fe3a240b94229b0bd9b3c6220a/pytest_httpserver/httpserver.py#L149) is typed as a string but when you do the comparison in [matcher](https://github.com/csernazs/pytest-httpserver/blob/32e1b2c9a005b1fe3a240b94229b0bd9b3c6220a/pytest_httpserver/httpserver.py#L209) you are comparing it to a byte-string, since requests query_string is a byte-string

Best regards

**Comment by csernazs** [comment]
Thanks for the bug report. I'll merge the fix for it soon.
