### ISSUE TITLE
remove stale branches

### ISSUE THREAD

**Issue by beliaev-maksim** [csernazs/pytest-httpserver#169]
please remove unused branches. Ideally keep only `master`
https://github.com/csernazs/pytest-httpserver/branches

For the future auto deleting could be enabled: https://github.com/csernazs/pytest-httpserver/settings

![image](https://user-images.githubusercontent.com/51964909/188174011-7c83c35f-b900-4808-8175-bf772ab3ab88.png)

**Comment by csernazs** [comment]
squash merging is already enabled. There are MRs where we want to keep the commits so I wouldn't force it.
I have also removed many branches, and enabled the Automatic delete options. I have some branches which aren't moving forward but I want to keep the contents in case I will have time to work on such as proxy support.

**Comment by beliaev-maksim** [comment]
@csernazs 
basic rule is that each PR should be as small as possible and be self consistent. That leads to the situations that every PR could be and should be squashed.

You can take example of huge projects. CPython, Django, requests, etc

**Comment by csernazs** [comment]
We have small PRs but I like that PRs to have commits with descriptive commit messages such as in #166. 
These PRs should not have been squashed, and I think it makes no sense to split this PR to 3 PRs.

Having one commit per PR is also fine and I have no problems if someone wants to squash the commits also (personally I prefer to tailor my commits in my git before pushing it to PR but YMMV).

**Comment by beliaev-maksim** [comment]
with above mentioned PR I would squash and merge together commit messages.
If commits could be separated as different features, then I would do 3 PRs out of 1.

I just share community standards, but it is up to the project to decide which way to go :)
