### ISSUE TITLE
Give a way to choose between listenning to IPV4 or IPV6

### ISSUE THREAD

**Issue by azmeuk** [csernazs/pytest-httpserver#182]
I want to test how my application behaves when making requests to http servers responding on IPV4 or IPV6 or both. I would love if there was a way to explicitly tell httpserver to listen on IPV6.

I have read the documentation about dual stack, but it does not cover my usecase. From what I read on #61 I understand that it cannot listen to both IP protocols, but this is not a big deal, I could run several unit tests.

I could create my own `httpserver_listen_address` fixture with `[::1]` as the hostname, but the `httpserver` fixture is session-wide and I don't want to choose between IPV4 and IPV6 for the whole session as I would like to test both.

Could a solution be to implement a `httpserver6` fixture that would only run on IPV6?

What do you think?

**Comment by csernazs** [comment]
Yes, I think that you could implement a new fixture as you suggested, which would listen on a different IP, so you would have two instances running in the same process, in two different threads, but that should not be an issue.

I think you could implement it in a similar way as the `make_httpserver` function [here](https://github.com/csernazs/pytest-httpserver/blob/master/pytest_httpserver/pytest_plugin.py#L42), with a more simplified API (you won't need flexibility there as it would be only for you). 

Alternatively, you could introduce a marker in pytest which would specify the IP protocol (4 or 6) and based on it, you could bind to ipv4 or 6, accordingly. Then you would need to run the tests twice (eg. from a shell script) by specifying either the 4 or the 6 marker.
This is what I did to test TLS, as it is a very similar problem as yours (I wanted to have a TLS server and a non-TLS one). As an example, see the commit e9a3a9dfe755ef27e885fc2fa35e8a9747fa2d4a.

**Comment by azmeuk** [comment]
I managed to build my ad-hoc ipv6 fixtures. Would you accept a PR for a `httpserver_ipv6` fixture, or is this out-of-scope for this library?

**Comment by csernazs** [comment]
I thought that this is a marginal issue but you are the second developer  dealing with ipv4 vs ipv6 things, and adding a new fixture won't harm anyone (assuming that the original keeps working), so I'm open to accept the PR.

Just I want to understand, the `httpserver_ipv6` would be different from the current `httpserver` one in the default listen address only, right? The ipv6 would listen on `::1` while the ipv4 would still listen on `localhost` which gets resolved to something by the OS or werkzeug.
And I guess we would need to change the `url_for` method also, right? Eg. to have `http://[::1]:1234/foobar` url as the result.

Anyway, if you submit the PR we can discuss it there.

**Comment by csernazs** [comment]
Hi @azmeuk ,

This has been published with version 1.0.7 of pytest-httpserver. I'm sorry for the delay, I totally forgot that I merged you PR so there should be a release.

Thanks for your contribution, I promise next time I'll release it quickly.

BR,
Zsolt
