### ISSUE TITLE
Raise error if any request is received

### ISSUE THREAD

**Issue by joshtemple** [csernazs/pytest-httpserver#190]
Hi, and thank you for this super useful project!

How would I write a test to assert that no requests are received by the test server?

I've tried using an `httpserver` with no matchers added, followed by a `wait` with `raise_assertions=True` and `stop_on_nohandler=True`, but I still get the error `AssertionError: Wait timeout occurred, but some handlers left`.

My code looks a bit like this:

```python
server_url = httpserver.url_for("/go")
env_vars = {"URL_ENV_VAR": server_url}

with patch.dict(os.environ, env_vars), httpserver.wait(
    raise_assertions=True, stop_on_nohandler=True, timeout=2
):
    ...
```

**Comment by csernazs** [comment]
Thanks! :)

You code raised `AssertionError` so I suppose that is ok, but you have problem with the message, referring to `but some handler left`, because there were no handlers added. Is that right?

**Comment by joshtemple** [comment]
Not quite. In this case, I would have expected no assertion, since there were no matchers, and no requests were made to the server.

I want to write a test that passes if no requests are made, and raises an assertion if _any_ request is made.

**Comment by csernazs** [comment]
Ah, I see, thanks for making it clear.

What about using the `log` attribute of the `httpserver` object? It contains the request-response pairs in a list of 2-element tuple. If it is empty: no requests has been received, it it is not, then some requests has been made to the server.

**Comment by joshtemple** [comment]
That seems to have worked nicely, I can just `assert not httpserver.log`. Thanks for the tip!
