### ISSUE TITLE
Latest release version mismatch

### ISSUE THREAD

**Issue by scarabeusiv** [csernazs/pytest-httpserver#20]
The tag says 3.0.2, the pypi says 0.3.2, some commits say the same yet changelog again talks about 3.0.2. In pypi archive when the code unpacks it also contians folder pytest-httpserver-3.0.2.

Could you perhaps release 0.3.3 and sync it everywhere in order to avoid confusion?

**Comment by csernazs** [comment]
Yup, sorry for the mistake, I'll fix it very soon. Thanks for the report.

**Comment by csernazs** [comment]
Done, 0.3.3 is out, with proper git tag. I have also removed 3.0.2 tag.
