### ISSUE TITLE
Can HTTPServer().handlers be modified from user code?

### ISSUE THREAD

**Issue by Wenir** [csernazs/pytest-httpserver#229]
Hi, I need to delete a specific item from the permanent handlers list while leaving all other handlers intact. I know that I can delete it from HTTPServer().handlers. But it is not listed in [API docs](https://pytest-httpserver.readthedocs.io/en/latest/api.html) like HTTPServerBase().port and I am unsure whether it is a part of the public interface and whether modifying it directly is recommended/allowed.

**Comment by Wenir** [comment]
Thank you for the answer! In my black-box tests, I shouldn't know the number of requests my app will perform so i think oneshot handlers will not work for me.

After more research, i found that i can store `RequestHandler` somewhere and call `respond_with_handler` multiple times. This is more suitable for me because i can update the response without removing and adding handlers with the same parameters again and again

**Comment by csernazs** [comment]
ok, added a test for your case :)
