### ISSUE TITLE
RFE: please start making github releases

### ISSUE THREAD

**Issue by kloczek** [csernazs/pytest-httpserver#262]
Is it possible next time on release new version make the github release to have entry on https://github.com/csernazs/pytest-httpserver/releases entries? 🤔

I'm asking because only on make gh release is spread notification about new release to those who have set watch->releases.

More about gh releases is possible to find on
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
https://github.com/marketplace/actions/github-release

**Comment by csernazs** [comment]
Hi @kloczek,

I think creating releases sounds reasonable and doable, altough the sdist is also available in pypi.

This is not 100% clear for me:
> I'm asking because only on make gh release is spread notification about new release to those who have set watch->releases.

Could you please clarify this a bit?

**Comment by csernazs** [comment]
Also, I see you opened quite a bunch of tickets on github for other projects with the same request. What is the purpose behind this?

**Comment by kloczek** [comment]
> Could you please clarify this a bit?

Create GH release spreads notifications to those which have set in your repo watch->release.
You don't need to put anything in release message (most of the maintainer makes GH releases with empty content).

**Comment by kloczek** [comment]
> Also, I see you opened quite a bunch of tickets on github for other projects with the same request. What is the purpose behind this?

I have automation which processes GH release email notifications.
This automation tries to upgrade rpm packages in distro on which I;m working.
In other words spreading such notifications allow save huge amount of time which not so long time ago was done manually.
(in distribution now is 4.6k source packages)
