### ISSUE TITLE
expect_result and expect_oneshot_request do no handle ?

### ISSUE THREAD

**Issue by jmichalik** [csernazs/pytest-httpserver#27]
when using:
`httpserver.expect_request(url_addition).respond_with_json(expected_result)`
if `url_addition` has a `?` in it, the server response fails (500).

Example of working `url_addition`:
`/widgetperiod=2020`

Example of non-working `url_addition`:
`/widget?period=2020`

This is something I need so I can't get around not having `?`. Please have a look.

**Comment by csernazs** [comment]
Could you please try the following?
`httpserver.expect_request("/widget", query_string="period=2020").respond_with_json(expected_result)`
You can also specify a dict to query_string if that's better for you (this looks a bit weird I know but we want to maintain API compatibility).

**Comment by jmichalik** [comment]
Seems to work. Thank you for the hint.
