### ISSUE TITLE
except_request can't handle `?` or `%3F`

### ISSUE THREAD

**Issue by aparcar** [csernazs/pytest-httpserver#28]
Hi, great plugin! I'm using it for one of my current projects and it works mostly great!

Today I came up with an error when the URL contains a `?` (question mark). The Server Fails with 500 no matter what I try. Is that a limitation of the query match implementation?

**Comment by csernazs** [comment]
No, this is not a limitation. It can match the query string if you provide the dictionary with the parameters.

See issue #27 

As it came up twice, it may need to be addressed somehow: either by raising an exception describing the problem or supporting the '?' in the URL.

I'm closing it now, but please reopen this issue if you still have a problem with this.

**Comment by aparcar** [comment]
Ugh, awkward. Sorry I did not find it. Thanks for the quick response!
