### ISSUE TITLE
Add a way to notify test code that all handers were executed

### ISSUE THREAD

**Issue by rominf** [csernazs/pytest-httpserver#3]
Now we have code like this:
```python
httpserver.expect_oneshot_request(...).respond_with_response(Response(status=200))                                                                             
# make request from external software, which doesn't expose responses to requests
wait_for_truthy(lambda: not httpserver.oneshot_handlers, description='all requests processed')
httpserver.check_assertions()
```
where `wait_for_truthy` is a function that periodically calls its first argument until either the result becomes `True` or a timeout occurs.
This solution is not very beautiful and fast. Do you have ideas about how to do this properly?

**Comment by csernazs** [comment]
Well, in this case I assume that the 3rd party software is doing the request in a separate thread or a process. Is that right?
So the problem is that we don't know when the processing finished. Would it be possible to wait for that thread (by joining to it) or to call wait() on that process which is making the requests?
Then you could safely check httpserver's status.

**Comment by rominf** [comment]
We are writing tests for our main product which is written in C++. The request is made in response to request that I'm sending to this program using requests. So, firstly, communication between Python and C++ application is not simple, secondly, we want to test it without knowing implementation details.

Do you have other proposals?

**Comment by rominf** [comment]
I propose to use store `threading.Event` or `threading.Condition` instance in `httpserver`.

**Comment by rominf** [comment]
Also it to would be great to combine it somehow with `httpserver.check_assertions` to fail as soon as wrong request arrives.

**Comment by csernazs** [comment]
In Linux you can wait for an file descriptor, thread or process. If you don't have any of these, only the polling will remain, however if you are creating the thread or the process from python directly, I would still suggest waiting on that object (fd, thread, process).
Polling is the last resort. Of course it would work in httpserver as well (let's say in a wait() method) httpserver which would do very similar to your code, but only the waiting would be there, calling the assertions would be the responsibility of the caller.

**Comment by rominf** [comment]
What's wrong with the method I described in https://github.com/csernazs/pytest-httpserver/issues/3#issuecomment-468897049? Will you accept my patch implementing this?

**Comment by csernazs** [comment]
If you have a patch for this, that would help me to understand your solution. I think I haven't understood fully what you need and that would help. I can't make any guarantee that the patch will be accepted but I'm ok with using threading events.

**Comment by csernazs** [comment]
I'll be off the grid for a few days, so don't expect timely response from me. I can get back to you mid next week.

**Comment by rominf** [comment]
See #6.
