### ISSUE TITLE
Project latest code and documentation not aligned with version published on pypy

### ISSUE THREAD

**Issue by christian-pinto** [csernazs/pytest-httpserver#343]
Hi many thanks for this library, it is super useful!!

The documentation of the project describe methods such as `assert_request_made` that were added in the code on April 3rd (commit b078e90) but are not part of v1.0.10 available on pypy. 

Are there any plans for updating the version of this library available on pypy?

**Comment by csernazs** [comment]
Yes, I plan to do the release in the coming days.

I'll let you know when the new version is released.

Thanks,
Zsolt

**Comment by christian-pinto** [comment]
Awesome,

Thanks

**Comment by csernazs** [comment]
@christian-pinto 
I've just released v1.0.11 with the feature you mentioned (amongst other features).
(you may need to specify `pytest-httpserver==1.0.11` for pip)

I'm closing this issue, if you spot any problems, please feel free to re-open it.

Thanks for your patience,

Zsolt
