### ISSUE TITLE
Type hints

### ISSUE THREAD

**Issue by gitpushdashf** [csernazs/pytest-httpserver#65]
Hi,

This is an awesome project! I'm trying to incorporate it into a codebase that has type checking done with mypy. It looks like the type hints aren't loaded because there's no py.typed file.

This generally requires creating a py.typed empty file and two extra lines in setup.py.

https://mypy.readthedocs.io/en/latest/installed_packages.html#creating-pep-561-compatible-packages

Is this something you would be interested in? I see there's some type hints already. It's not a bad idea to test the hints with mypy, either.

Thank you!

**Comment by csernazs** [comment]
Hi,

Sorry for the late answer.

Currently I use type hints ad-hoc in the library to improve IDE support for it (eg. to have tab completion on the objects).
I have some experience with mypy on other projects, it has many upside but also have downside as well, it requires sometimes the code to be written in a way which is "good" for it. I can give it a try on pytest-httpserver and see how well it works.

I'm happy to add py.typed file, but it is not entirely clear for me that why py.typed is required? What if I don't ship with the library?
I've skimmed through PEP 561 but haven't found out it yet.
I found a stackoverflow question which makes it a bit more clear for me (https://stackoverflow.com/questions/62979389/is-there-a-best-practice-to-make-a-package-pep-561-compliant), so it seems that if your code uses an external library then you cannot check the types provided with that library if that py.typed file does not exist.

**Comment by csernazs** [comment]
Yes, it is time to deprecate the older python releases. Python 3.5 reached EOL one year ago.. Although I wanted to support as many cores as I can do, this causes syntax error so it cannot be avoided (unless by generating a different wheel, but I think that's too much effort compared to supporting a deprecated core).
I've added release notes also, I think will go ahead with the merge, but I do want to look at the strict errors also later.

**Comment by gitpushdashf** [comment]
My bad, looks like there is a slight issue.

My tests look like this:

```
from pytest_httpserver import HTTPServer

TEST_CONTENTS = b"I am testing."


@pytest.fixture(scope="session")
def test_url() -> Iterator[str]:
    with HTTPServer() as httpserver:
        httpserver.expect_request("/testing", method="GET").respond_with_data(
            TEST_CONTENTS
        )
        yield httpserver.url_for("/testing")
```

Which mypy complains about here: `error: Module "pytest_httpserver" does not explicitly export attribute "HTTPServer"; implicit reexport disabled
Found 1 error in 1 file`

This explicit export error is annoying. I think to solve it, I can do `from pytest_httpserver.httpserver import HTTPServer`, or `__init__.py` has to look like this:

```
from .httpserver import HTTPServer as HTTPServer
...
```

Alternatively, I think __all__ can be set.

https://github.com/konradhalas/dacite/issues/133

`from pytest_httpserver.httpserver import HTTPServer` is working for me. I don't quite understand the implicit export behavior in mypy. I guess maybe there's cases where `__init__.py` might have imports which it doesn't want to export.

**Comment by gitpushdashf** [comment]
Looks like you fixed this here: https://github.com/csernazs/pytest-httpserver/commit/3533aafdfa462e09f5b2bcdc7a140376bf1ffd70

Thank you!

Are you planning to cut a new release any time soon?

**Comment by csernazs** [comment]
Yup, 1.0.3 is out.
I'm closing this but let me know if you have any issue(s).

**Comment by gitpushdashf** [comment]
Works perfectly! Thank you!
