### ISSUE TITLE
Start HTTPServer on ephemeral port by default

### ISSUE THREAD

**Issue by rominf** [csernazs/pytest-httpserver#8]
Now:
1. Port 4000 can be used already.
2. It's not possible to run tests in parallel.

I propose to set:
```python
HTTPServer.DEFAULT_LISTEN_PORT = 0
```
to solve this.

**Comment by csernazs** [comment]
I'm ok with supporting ephemeral ports, I already accepted PR #7.

Having it as the default could also work - there could be scenarios where fixed port is better (having an application to be tested which could not be configured  or difficult to reconfigure anyway), but in those cases the users can still set their ports.

Running tests in parallel is a more difficult thing as starting the server takes about 1 seconds maximum and currently it is optimized by having a single server instance in the memory so people not running the tests in parallel can also run tests faster. It would need to have some method so specify that "I want to start a new server" or "I want to reuse my previous server".

**Comment by rominf** [comment]
OK, I understand. Anyway, should I make a PR changing the default port to 0?

**Comment by csernazs** [comment]
Yes, sure.
