### ISSUE TITLE
Unify expect_oneshot_request and expect_request

### ISSUE THREAD

**Issue by rominf** [csernazs/pytest-httpserver#9]
`expect_oneshot_request` and `expect_request` are responsible for similar actions, but `expect_oneshot_request` takes one optional keyword argument more (`ordered`). I propose to:
1. Define enum `HandlerType`:
```python
class HandlerType(Enum):
    PERMANENT = 'permanent'
    ONESHOT = 'oneshot'
    ORDERED = 'ordered'
```
2. Make `expect_request` universal so that it could register permanent, oneshot, and ordered handlers by adding optional enum `HandlerType` argument.
3. Remove `ordered` argument from `expect_oneshot_request`.
4. Add convinience method `expect_ordered_request`.

**Comment by csernazs** [comment]
That's a good idea.
And the code would also be better because `self.create_matcher` would be called at only one place, in the `expect_request` method.

**Comment by csernazs** [comment]
The optional keyword argument could be `type` or something like that, as `ordered=HandlerType.ONESHOT` does not look good, as having a oneshot rule is orthogonal to whether it is ordered or not.
But this is just about the naming. :)
